bazelisk: do not depend on binary distribution, support aarch64
sudoforge/pkgbuilds pull request #47
Opened 2021-05-29 18:01 UTC by wijagels

2021-05-29 18:04 UTC, sudoforge commented
Can I ask you to clarify whether or not you are talking about dogfooding the tool in order to build the non-binary package?

2021-05-29 18:13 UTC, wijagels commented
Right, instead of grabbing a prebuilt bazelisk I'm using `go build` to create an intermediate copy of bazelisk to build the final bazelisk. Pretty much the same process as the bazelisk release script: https://github.com/bazelbuild/bazelisk/blob/master/build.sh

A simpler (and faster) approach would be to just call `GOOS=linux GOARCH=amd64 go build -o bazel` and package that.

2021-05-29 19:49 UTC, sudoforge commented
My apologies, my earlier comment was left when I was in the middle of a few things and I didn't get a chance to look at the diff that was proposed.

So, I'd prefer leaning toward a different approach to this, namely, providing architecture-specific sources instead of adding `go` as a makedep and increasing the overall build time of the package by daisy-chaining builds as this CL is currently doing.

I'm out of town for a wedding and am on mobile at the moment, but if you're open to refactoring the CL to take the general approach I suggested above I'd be happy to review and merge it when I have the chance later tonight or tomorrow morning (in a UTC-0700 time zone currently).

2021-05-29 19:53 UTC, sudoforge commented
A quick additional note -- I'd prefer avoiding using `go` directly as this can potentially lead to requiring additional steps that the build target defined in the BUILD file already covers; one of the main points of Bazel is to provide abstractions for building targets, and as that is what is used internally, it would be more canonical to follow that approach for this package.

2021-05-29 21:42 UTC, wijagels commented
Makes sense, I updated the change to grab a bazel release and unpack that in the build directory. Let me know what you think of this solution.

2021-05-30 18:03 UTC, sudoforge requested changes

2021-05-30 19:03 UTC, wijagels commented on bazelisk/PKGBUILD
> +  ${_bazel} --output_user_root=${PWD}/bazel_tmp --max_idle_secs=5 \
The motivation is to keep the build from affecting anything outside of srcdir. Without this, bazelisk and all of its build dependencies (~900M) will persist in `~/.cache/bazel/` and can't be removed with makepkg --clean.

2021-05-31 14:57 UTC, sudoforge commented on bazelisk/PKGBUILD
> +  ${_bazel} --output_user_root=${PWD}/bazel_tmp --max_idle_secs=5 \
Heh, that's actually what I think would be preferred -- namely, that users are able to reuse the cache between builds of the package regardless of whether or not they were cleaning the build directories.

I've taken this similar approach in the past -- do you think it is an anti-pattern?

2021-05-31 15:24 UTC, wijagels commented on bazelisk/PKGBUILD
> +  ${_bazel} --output_user_root=${PWD}/bazel_tmp --max_idle_secs=5 \
Looking closer at other packages, I don't see this technique in use. I'll get rid of it.

2021-05-31 16:10 UTC, sudoforge requested changes
Thanks again for working on this! I'm traveling back home today and will be back online in roughly 10 hours (~ 20:00 UTC-0600 / 8pm MDT). I'll take a look at this again if you've sent an update.

Also, I can't leave a comment on the appropriate line because of a limitation in GitHub's file review feature, however, please feel free to add your information on line 2, following the same format as the current value of line 2 (which should be moved to line 3).

2021-05-31 16:45 UTC, wijagels commented on bazelisk/PKGBUILD
> +  ${_bazelisk} --max_idle_secs=5 build -c opt //:bazelisk-linux-${target}
- It would kick in where the build step exits early, but I can get rid of it.

- I did look into using --config=release but that winds up calling git to embed the commit. That information won't be correct since this isn't the -git package. It does look silly without the stamp: `Bazelisk version: {STABLE_VERSION}` so I'll fix that.

- Will do

2021-05-31 16:45 UTC, wijagels commented on bazelisk/PKGBUILD
>  source=(
The behavior I've observed is that architecture specific sources are appended to the source list.

2021-06-02 23:28 UTC, sudoforge requested changes
thanks again for the effort you've put into this! after addressing these few review comments i'll be happy to merge this in :)

2024-07-23 02:18 UTC, closed without merging