[fix] gracefully handle no "updpkgsums" in packages hooks
sudoforge/pkgbuilds pull request #84
Opened 2023-02-05 00:54 UTC by jmelahman

Without installed:
```
$ git commit -m 'foo'
[ buildifier-bin ] setting pkgrel to '1'
[ buildifier-bin ] updating package checksums... FAIL
Command 'updpkgsums' not found. Try installing 'pacman-contrib'.

```

With installed:
```
$ git commit -m 'foo'
[ buildifier-bin ] setting pkgrel to '1'
[ buildifier-bin ] updating package checksums... OKAY
[ buildifier-bin ] updating .SRCINFO... OKAY
[jamison/buildifier-6 cc2e0eb] foo
 3 files changed, 10 insertions(+), 6 deletions(-)

```

2023-02-19 13:41 UTC, sudoforge requested changes
Thanks for this. We should probably do the same with `makepkg` and `git`, too.

Do you mind abstracting this out into a loop that checks these three dependencies, prints out an error message for each that is missing, and then exits with `1` (if any were missing)?

2023-03-12 08:20 UTC, jmelahman commented
> Thanks for this. We should probably do the same with `makepkg` and `git`, too.
> 
> Do you mind abstracting this out into a loop that checks these three dependencies, prints out an error message for each that is missing, and then exits with `1` (if any were missing)?

Done

2023-03-12 08:34 UTC, jmelahman commented on .githooks.d/pre-commit/packages.sh
> +_RUNTIME_DEPS=('updpkgsums' 'makepkg' 'git')
FYI, I haven't tried to write POSIX compliant shell before. Shellcheck complains the following, but there are similar warnings throughout this script, so not sure if these are worrisome,
```
In ./.githooks.d/pre-commit/packages.sh line 5:
_RUNTIME_DEPS=('updpkgsums' 'makepkg' 'git')
              ^----------------------------^ SC3030 (warning): In POSIX sh, arrays are undefined.


In ./.githooks.d/pre-commit/packages.sh line 8:
  local missing_deps=()
  ^----------------^ SC3043 (warning): In POSIX sh, 'local' is undefined.
                     ^-- SC3030 (warning): In POSIX sh, arrays are undefined.


In ./.githooks.d/pre-commit/packages.sh line 9:
  for d in "${_RUNTIME_DEPS[@]}"; do
            ^-----------------^ SC3054 (warning): In POSIX sh, array references are undefined.


In ./.githooks.d/pre-commit/packages.sh line 11:
      missing_deps+=("$d")
      ^----------^ SC3024 (warning): In POSIX sh, += is undefined.
                    ^----^ SC3030 (warning): In POSIX sh, arrays are undefined.


In ./.githooks.d/pre-commit/packages.sh line 16:
    for d in "${missing_deps[@]}"; do
              ^----------------^ SC3054 (warning): In POSIX sh, array references are undefined.


In ./.githooks.d/pre-commit/packages.sh line 17:
      >&2 printf "Command '$d' not found.\n"
                 ^-------------------------^ SC2059 (info): Don't use variables in the printf format string. Use printf '..%s..' "$foo".


In ./.githooks.d/pre-commit/packages.sh line 19:
    >&2 printf "Hint: use 'pacman -F ${missing_deps[*]}' to determine which packages to install."
               ^-- SC2059 (info): Don't use variables in the printf format string. Use printf '..%s..' "$foo".
                                     ^----------------^ SC3054 (warning): In POSIX sh, array references are undefined.
```

Happy to address any issue, but as-is looks most familiar to me.

2023-03-12 08:37 UTC, sudoforge commented on .githooks.d/pre-commit/packages.sh
> +_RUNTIME_DEPS=('updpkgsums' 'makepkg' 'git')
`shellcheck` is indeed correct; those arrays you're used to using are supported in `bash`, but are not part of the POSIX standard.

a good ol' space-separated string (which you call without quotes; see below) is all we need.

```
DEPS="foo bar baz"

for dep in $DEPS; do
    ...
done
```

2023-03-16 17:49 UTC, sudoforge requested changes
thanks for abstracting this out into a function! i have a few recommendations for improving readability and formatting; feel free to apply these as-is or use as inspiration for refactoring it yourself.

2023-03-17 06:39 UTC, jmelahman commented on .githooks.d/pre-commit/packages.sh
> +
Thank you

2024-07-23 02:16 UTC, sudoforge commented
sorry this never merged; i have moved on from maintaining these packages. i'll merge this in-tree, but will be archiving the repository shortly.

2024-07-23 02:17 UTC, sudoforge approved these changes

2024-07-23 02:18 UTC, merged